name: Build and Release

on:
  push:
    branches:
    - '**'
    tags-ignore:
    - '**'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GOOS: linux
      GOARCH: amd64
      CGO_ENABLED: "0"

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: "./go.mod"

    - run: go mod download
    - run: go build -ldflags="-X main.GitCommit=${{ github.sha}}"
    - run: go test -v ./...

    - run: echo "VERSION=$(./nomad-listener --version)" >> "${GITHUB_ENV}"

    - id: release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.VERSION }}
        body: ""
        prerelease: ${{ github.ref_name != 'main' }}
        make_latest: ${{ github.ref_name == 'main' }}
        files: nomad-listener
